INSERT INTO oppilas VALUES (0, 'quuppa', 'q', 0, '2014-01-08 04:05:06');
INSERT INTO oppilas VALUES (1, 'Ana', 'ana', 0, '2014-01-08 04:05:06');
INSERT INTO oppilas VALUES (2, 'Kaarina', 'salasana', 0, '2014-01-08 04:05:06');
INSERT INTO oppilas VALUES (3, 'Erkki', 'passu', 0, '2014-01-08 04:05:06');
INSERT INTO opettaja VALUES (0, 'Ope', 'ope', '{0, 1, 2}');
INSERT INTO opettaja VALUES (1, 'Maikka', 'ope', '{0}');
INSERT INTO sana VALUES (0, 'blue', 'eng-suo', 'sininen', '', 'substantiivi','');
INSERT INTO sana VALUES (1, 'red', 'eng-suo', 'punainen', '', 'substantiivi','');
INSERT INTO sana VALUES (2, 'yellow', 'eng-suo', 'keltainen', '', 'substantiivi','');
INSERT INTO sana VALUES (3, 'green', 'eng-suo', 'vihreä', '', 'substantiivi','');
INSERT INTO sana VALUES (4, 'black', 'eng-suo', 'musta', '', 'substantiivi','');
INSERT INTO sana VALUES (5, 'white', 'eng-suo', 'valkoinen', '', 'substantiivi','');
INSERT INTO sana VALUES (6, 'driver', 'eng-suo', 'ajuri', '', 'substantiivi','');
INSERT INTO sana VALUES (7, 'byte', 'eng-suo', 'tavu', '', 'substantiivi','');
INSERT INTO sana VALUES (8, 'motherboard', 'eng-suo', 'emolevy', '', 'substantiivi','');
INSERT INTO sana VALUES (9, 'hard drive', 'eng-suo', 'kiintolevy', '', 'substantiivi','');
INSERT INTO sana VALUES (10, 'broadband', 'eng-suo', 'laajakaista', '', 'substantiivi','');
INSERT INTO sana VALUES (11, 'square root', 'eng-suo', 'neliöjuuri', '', 'substantiivi','');
INSERT INTO sana VALUES (12, 'derivative', 'eng-suo', 'derivaatta', '', 'substantiivi','');
INSERT INTO sana VALUES (13, 'number theory', 'eng-suo', 'lukuteoria', '', 'substantiivi','');
INSERT INTO sana VALUES (14, 'vector', 'eng-suo', 'vektori', '', 'substantiivi','');
INSERT INTO sana VALUES (15, 'prime number', 'eng-suo', 'alkuluku', '', 'substantiivi','');
INSERT INTO sana VALUES (16, 'induction', 'eng-suo', 'induktio', '', 'substantiivi','');
INSERT INTO sana VALUES (17, 'probability integral', 'eng-suo', 'kertymäfunktio', '', 'substantiivi','');
INSERT INTO sanasto VALUES (1, 'Värit', 'eng-suo', 'Värejä ja sävyjä', 6, '27/09/2014', 0);
INSERT INTO sanasto VALUES (2, 'Tietotekniikka 1', 'eng-suo', 'ICT-perussanastoa', 5, '27/09/2014', 1);
INSERT INTO sanasto VALUES (3, 'Matikka 1', 'eng-suo', 'Matematiikan termejä', 7, '27/09/2014', 0);
INSERT INTO kuuluu VALUES (0, 1);
INSERT INTO kuuluu VALUES (1, 1);
INSERT INTO kuuluu VALUES (2, 1);
INSERT INTO kuuluu VALUES (3, 1);
INSERT INTO kuuluu VALUES (4, 1);
INSERT INTO kuuluu VALUES (5, 1);
INSERT INTO kuuluu VALUES (6, 2);
INSERT INTO kuuluu VALUES (7, 2);
INSERT INTO kuuluu VALUES (8, 2);
INSERT INTO kuuluu VALUES (9, 2);
INSERT INTO kuuluu VALUES (10, 2);
INSERT INTO kuuluu VALUES (11, 3);
INSERT INTO kuuluu VALUES (12, 3);
INSERT INTO kuuluu VALUES (13, 3);
INSERT INTO kuuluu VALUES (14, 3);
INSERT INTO kuuluu VALUES (15, 3);
INSERT INTO kuuluu VALUES (16, 3);
INSERT INTO kuuluu VALUES (17, 3);
INSERT INTO sana VALUES (18, 'grey', 'eng-suo', 'harmaa', '', 'substantiivi','');
INSERT INTO kuuluu VALUES (18, 1);